package org.fukuii.consensus.pow.certification

import org.scalatest.flatspec.AnyFlatSpec

import org.fukuii.consensus.pow.{Ethash, EthashDataset}
import org.fukuii.evm.fixtures.{FixtureCorpus, Heavy, PoWFixture}

/** The FULL dataset at a real epoch's size, against the published answers.
  *
  * ==Why this exists when `EthashVectorPropSpec` already certifies the
  * construction byte for byte==
  *
  * That spec builds thirty-two kilobytes and compares every byte against a
  * reference client's literal, which is the stronger check of the two and the
  * only one available at any size. What it cannot reach is **scale**: a real
  * epoch is sixteen million items rather than five hundred, its indices run
  * past the point where a narrower integer would wrap, and the array it lives
  * in is a gigabyte. Those are properties of the size and of nothing else, so
  * they need the size.
  *
  * ==What it is checked against, given that no published value states a real
  * dataset's contents==
  *
  * The two cases the `PoWTests` tier publishes, evaluated through the dataset
  * rather than through the cache. Their `mixHash` and `result` are stated by an
  * outside party, so agreement is not the two paths agreeing with each other --
  * it is the dataset path agreeing with the ecosystem, at the size a network
  * actually runs.
  *
  * ==Nothing is written to disk==
  *
  * The dataset is built in memory and discarded. A real client persists one and
  * memory-maps it, which is a node's storage concern rather than a rule's, and
  * a gigabyte of generated bytes has no business anywhere near a working tree.
  */
class FullDatasetCertificationSpec extends AnyFlatSpec:

  private val cases: Vector[PoWFixture] =
    FixtureCorpus.root.toVector.flatMap { root =>
      FixtureCorpus
        .jsonFilesUnder(root.resolve("ethereum/tests/PoWTests"))
        .flatMap { file =>
          FixtureCorpus
            .read(file)
            .flatMap(PoWFixture.decodeFile(file.getFileName.toString, _))
            .getOrElse(Vector.empty)
        }
    }

  /** The dataset sizes the published cases state.
    *
    * Read off the cases rather than assumed, so a corpus that gained a case at
    * another epoch fails here rather than being silently evaluated against a
    * dataset that is not its own.
    */
  private val statedSizes: Set[Long] = cases.map(_.datasetSize).toSet

  private lazy val dataset: EthashDataset =
    Ethash.datasetFor(Ethash.cacheFor(BigInt(0), Ethash.EpochLength), Ethash.datasetSize(BigInt(0)))

  "the published cases" should "all state the first epoch's dataset size" in
    assert(
      statedSizes == Set(Ethash.datasetSize(BigInt(0))),
      "a case at another epoch needs its own dataset, and evaluating it against this one would answer nonsense: " +
        statedSizes.toString
    )

  it should "be found at all" in
    assert(
      cases.length == 2,
      "found " + cases.length.toString + " cases: a run that built a gigabyte and compared it to nothing has " +
        "measured nothing, and set " + FixtureCorpus.RootVariable + " if this is a machine without the corpus"
    )

  "a full dataset at the first epoch's real size" should "answer every published case exactly" taggedAs Heavy in
    assert(
      cases.forall { fixture =>
        val answered = Ethash.evaluateFull(dataset, fixture.headerHash, fixture.nonce.toIArray)
        answered.mixHash == fixture.mixHash && answered.result == fixture.result
      },
      "the dataset path disagrees with the published answers at a size no reference literal states"
    )

  it should "hold exactly the bytes the size calls for" taggedAs Heavy in
    assert(
      dataset.size == Ethash.datasetSize(BigInt(0)),
      "answered " + dataset.size.toString + " rather than " + Ethash.datasetSize(BigInt(0)).toString
    )
