package org.fukuii.types

import org.fukuii.bytes.{BytesError, FixedWidth, Hex}
import org.fukuii.crypto.Keccak256
import org.fukuii.rlp.{RlpCodec, RlpError, RlpItem}

/** The 2048-bit Bloom filter over the indexable information — logger address
  * and log topics — in a block's receipts.
  *
  * 2048 bits is 256 bytes, and the Yellow Paper states the width in bits at the
  * point it asserts the receipt's own field, so the byte figure is derived
  * rather than quoted.
  *
  * Constructed by [[Bloom.fromLogs]], which is the Yellow Paper's `M(O)`.
  */
final class Bloom private (private val raw: IArray[Byte]):

  def toBytes: IArray[Byte] = raw

  def toHex: String = Hex.encode(raw)

  override def equals(that: Any): Boolean = that match
    case other: Bloom => FixedWidth.sameBytes(raw, other.raw)
    case _            => false

  override def hashCode(): Int = FixedWidth.hash(raw)

  /** Truncated on both ends. A full bloom is 512 hex characters and is almost
    * always mostly zero, so printing it whole buries whatever line carries it.
    */
  override def toString: String =
    val hex = Hex.encode(raw)
    "0x" + hex.take(8) + "…" + hex.takeRight(8)

object Bloom:

  val Width: Int = 256

  /** Requires exactly [[Width]] bytes. */
  def fromBytes(bytes: IArray[Byte]): Either[BytesError, Bloom] =
    if bytes.length == Width then Right(new Bloom(FixedWidth.align(bytes, Width)))
    else Left(BytesError.BadWidth(Width, bytes.length))

  def fromHex(s: String): Either[BytesError, Bloom] =
    Hex.decode(s).left.map(BytesError.BadHex.apply).flatMap(fromBytes)

  /** All bits clear — the bloom of a block whose receipts carry no log. */
  val Empty: Bloom = new Bloom(IArray.unsafeFromArray(new Array[Byte](Width)))

  /** The Yellow Paper's `M(O)`: the bloom over a series of logs.
    *
    * Each log contributes its **indexable** information — the logger's address
    * and each of its topics, one entry apiece. Its data contributes nothing, so
    * two logs differing only in data produce one identical bloom.
    *
    * ==Three bits per entry, and the index is inverted==
    *
    * An entry sets three bits, taken from the first three 16-bit big-endian
    * groups of its Keccak-256 hash: for each, the low 11 bits give a number
    * `m` in `0..2047`, and the bit set is `2047 - m`, counted from **zero at
    * the most significant bit of byte 0**.
    *
    * **The subtraction is the part an implementation gets wrong silently.**
    * Without it the filter is a bit-reversed image of the real one: it is
    * self-consistent, every membership test it answers about its own output is
    * right, and it disagrees with the network on every block that carries a
    * log. Only a vector from outside this codebase catches that, which is why
    * these are generated by running the specification rather than written here.
    *
    * ==Combining is `or`, and both of its properties are load-bearing==
    *
    * Bits are only ever set, so the bloom of several logs is the bitwise `or`
    * of their individual blooms — associative, which is why a block's bloom may
    * equally be taken over every log at once or folded from its receipts', and
    * idempotent, which is why a repeated entry sets nothing twice. An
    * accumulator using addition or exclusive-or agrees on every distinct entry
    * and diverges the moment one repeats.
    */
  def fromLogs(logs: Seq[Log]): Bloom =
    val bits = new Array[Byte](Width)
    logs.foreach { log =>
      addEntry(bits, log.address.toBytes)
      log.topics.foreach(topic => addEntry(bits, topic.toBytes))
    }
    new Bloom(IArray.unsafeFromArray(bits))

  /** Sets one entry's three bits in place.
    *
    * Mutates rather than returning, because the alternative allocates a
    * 256-byte array per entry and a block's receipts carry thousands. The array
    * never escapes [[fromLogs]], which is what makes that safe.
    */
  private def addEntry(bits: Array[Byte], entry: IArray[Byte]): Unit =
    val hashed = Keccak256.hash(entry).toBytes
    var pair   = 0
    while pair < 6 do
      val low11 = (((hashed(pair) & 0xff) << 8) | (hashed(pair + 1) & 0xff)) & 0x7ff
      val index = 0x7ff - low11
      bits(index >>> 3) = (bits(index >>> 3) | (1 << (7 - (index & 7)))).toByte
      pair += 2

  /** Fixed-width, so its leading zeros are part of it: an empty bloom is 256
    * zero bytes and encodes as such, never as the empty string a scalar zero
    * would take.
    */
  given bloomCodec: RlpCodec[Bloom] with
    def encode(value: Bloom): RlpItem = RlpItem.Bytes(value.toBytes)
    def decode(item: RlpItem): Either[RlpError, Bloom] = item match
      case RlpItem.Bytes(payload) =>
        Bloom.fromBytes(payload).left.map(_ => RlpError.WrongWidth(Width, payload.length))
      case _: RlpItem.Sequence => Left(RlpError.ExpectedBytes)
