package org.fukuii.trie

import org.fukuii.bytes.{Address, Bytes, Hash, UInt256, UInt64}
import org.fukuii.rlp.RlpCodec
import org.scalatest.propspec.AnyPropSpec
import org.scalatest.prop.TableDrivenPropertyChecks

/** Published state roots, which are two levels rather than one.
  *
  * ==What a flat trie vector structurally cannot certify==
  *
  * `ethereum/tests` TrieTests drives one trie over opaque byte strings. A state
  * root roots each account's own storage trie first, embeds that root in the
  * account's encoding, and only then has an account leaf to insert. An
  * implementation can reproduce every flat vector and still order the two
  * levels the other way round, secure one level and not the other, or encode
  * an account's four fields out of order — none of which any flat vector
  * reaches.
  *
  * Every row is generated by `scripts/gen-state-root-vectors.py` from a
  * published fixture's genesis `pre` allocation, and gated against that
  * fixture's own `genesisBlockHeader.stateRoot` by driving the executable
  * specification's state over the same accounts. A row reaching this file has
  * been agreed on by two sources that are not fukuii.
  *
  * ==The instrument is checked for discriminating power, not assumed to have it==
  *
  * A table of roots that a broken implementation would also satisfy certifies
  * nothing, so one property below builds the state in the wrong order on
  * purpose and requires the root to move. Without it, "the roots match" is
  * consistent with the two levels never having been composed at all.
  */
class StateRootPropSpec extends AnyPropSpec with TableDrivenPropertyChecks:

  import TrieFixtures.implementations

  final private case class Slot(key: UInt256, value: UInt256)

  final private case class AccountRow(
      address: Address,
      nonce: UInt64,
      balance: UInt256,
      codeHash: Hash,
      slots: Seq[Slot]
  )

  final private case class StateVector(label: String, root: String, accounts: Seq[AccountRow]):
    def carriesStorage: Boolean = accounts.exists(_.slots.nonEmpty)

  private val ExpectedVectorCount: Int = 135

  private val vectors: Seq[StateVector] =
    val stream = Option(getClass.getResourceAsStream("/state-root-vectors.txt"))
      .getOrElse(
        throw new IllegalStateException("state-root-vectors.txt is not on the test classpath")
      )
    val source = scala.io.Source.fromInputStream(stream)
    try
      val lines = source.getLines().filterNot(l => l.isEmpty || l.startsWith("#")).toVector
      split(lines).map(parseRecord)
    finally source.close()

  /** One record per `case` line, its `acct` and `slot` lines following it. */
  private def split(lines: Seq[String]): Seq[Seq[String]] =
    lines.foldLeft(Vector.empty[Vector[String]]) { (records, line) =>
      if line.startsWith("case ") then records :+ Vector(line)
      else records.updated(records.length - 1, records.last :+ line)
    }

  private def parseRecord(record: Seq[String]): StateVector =
    val head = record.head.split(" ")
    val accounts = record.tail.foldLeft(Vector.empty[AccountRow]) { (rows, line) =>
      val fields = line.split(" ")
      if fields(0) == "acct" then
        rows :+ AccountRow(
          address = Address.fromHex(fields(1)).toOption.get,
          nonce = UInt64.fromHex(fields(2)).toOption.get,
          balance = UInt256.fromHex(fields(3)).toOption.get,
          codeHash = Hash.fromHex(fields(4)).toOption.get,
          slots = Vector.empty
        )
      else
        val slot = Slot(UInt256.fromHex(fields(1)).toOption.get, UInt256.fromHex(fields(2)).toOption.get)
        rows.updated(rows.length - 1, rows.last.copy(slots = rows.last.slots :+ slot))
    }
    StateVector(head(1), head(2), accounts)

  private def stateTrie(make: TrieFixtures.Build): StateTrie =
    new StateTrie(
      make(Securing.Secured),
      _ => make(Securing.Secured),
      TrieFixtures.store(),
      TrieFixtures.namespace("code")
    )

  /** A slot's key is the 32-byte slot NUMBER, left-padded before the trie
    * secures it — the published form is minimal, and hashing it at its
    * published width hashes a different pre-image entirely. Its value is the
    * RLP of the word, which is where a zero would become a leaf holding `0x80`
    * rather than no leaf at all; the generator drops zeros for that reason and
    * no row here carries one.
    */
  private def writeStorage(state: StateTrie, account: AccountRow): Unit =
    val storage = state.storage(account.address)
    account.slots.foreach { slot =>
      storage.put(Bytes.fromIArray(slot.key.toBytes), Bytes.fromIArray(RlpCodec.encodeTo(slot.value)))
    }

  private def build(state: StateTrie, vector: StateVector): StateTrie =
    vector.accounts.foreach { account =>
      writeStorage(state, account)
      state.putAccount(account.address, account.nonce, account.balance, account.codeHash)
    }
    state

  private val builds = Table(("implementation", "build"), implementations*)
  private val rows = Table("vector", vectors*)
  private val storageRows = Table("vector", vectors.filter(_.carriesStorage)*)

  property("every implementation reproduces every published state root") {
    forAll(builds) { (implementation: String, make: TrieFixtures.Build) =>
      forAll(rows) { (vector: StateVector) =>
        assert(
          build(stateTrie(make), vector).stateRoot.toHex == vector.root,
          implementation + " disagrees with the published state root for " + vector.label
        )
      }
    }
  }

  /** The account leaf commits to the storage root as it stood when the leaf was
    * written, so writing the leaf first commits to an empty storage trie. This
    * requires the published roots to detect that, which is the whole reason the
    * two-level bar is separate from the flat one.
    */
  property("writing an account leaf before its storage produces a different root") {
    forAll(builds) { (implementation: String, make: TrieFixtures.Build) =>
      forAll(storageRows) { (vector: StateVector) =>
        val state = stateTrie(make)
        vector.accounts.foreach { account =>
          state.putAccount(account.address, account.nonce, account.balance, account.codeHash)
          writeStorage(state, account)
        }
        assert(
          state.stateRoot.toHex != vector.root,
          implementation + " reached the published root for " + vector.label +
            " with the two levels composed in the wrong order, so these vectors cannot detect that defect"
        )
      }
    }
  }

  property("the table carries the expected number of published state roots") {
    assert(
      vectors.length == ExpectedVectorCount,
      "a different count means the generator dropped a vector or the fixture release moved"
    )
  }

  /** A table of accounts that all have empty storage would pass every root
    * above while certifying only the account trie — the flat half this bar
    * exists to go beyond.
    */
  property("the table carries accounts whose storage tries are not empty") {
    assert(
      vectors.count(_.carriesStorage) > 0 && vectors.exists(_.accounts.exists(_.slots.length >= 4)),
      "without accounts carrying several storage slots, nothing here exercises the second level"
    )
  }
